name       : xdg-desktop-portal-kde
version    : 5.19.3
release    : 37
source     :
    - https://cdn.download.kde.org/stable/plasma/5.19.3/xdg-desktop-portal-kde-5.19.3.tar.xz : da2ca69694230d560066b63fe3a4eec280fdc2981b521eb794acf4b629b3a013
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-or-later
component  : desktop.kde
summary    : Qt/KDE for xdg-desktop-portal
description: |
    A backend implementation for xdg-desktop-portal that is using Qt/KDE.
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(Qt5Quick)
    - cups-devel
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdeclarative-devel
    - ki18n-devel
    - kirigami2-devel
    - kio-devel
    - knotifications-devel
    - kwayland-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - plasma-framework-devel
rundeps    :
    - xdg-desktop-portal
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
