name       : xdg-desktop-portal-kde
version    : 5.14.3
release    : 6
source     :
    - https://cdn.download.kde.org/stable/plasma/5.14.3/xdg-desktop-portal-kde-5.14.3.tar.xz : 033d5ee910bd7a81dc3788af7dfc526627809ab6bd8ad99c3ade5048fd380b3c
license    : LGPL-2.1-or-later
component  : desktop.kde
summary    : Qt/KDE for xdg-desktop-portal
description: |
    A backend implementation for xdg-desktop-portal that is using Qt/KDE.
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(glib-2.0)
    - pkgconfig(libpipewire-0.2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - knotifications-devel
    - kwayland-devel
    - kwidgetsaddons-devel
rundeps    :
    - xdg-desktop-portal
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
