name       : xdg-desktop-portal-kde
version    : 5.27.5
release    : 73
source     :
    - https://cdn.download.kde.org/stable/plasma/5.27.5/xdg-desktop-portal-kde-5.27.5.tar.xz : 7cfa3f24cff9b18baeef245e122f969092a89c41d872ea5a8df628061d8f1aab
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-or-later
component  : desktop.kde
summary    : Qt/KDE for xdg-desktop-portal
description: |
    A backend implementation for xdg-desktop-portal that is using Qt/KDE.
builddeps  :
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(epoxy)
    - pkgconfig(dri)
    - pkgconfig(xkbcommon)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-server)
    - cups-devel
    - kdeclarative-devel
    - kglobalaccel-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - knotifications-devel
    - kwayland-devel
    - plasma-framework-devel
    - plasma-wayland-protocols-devel
rundeps    :
    - xdg-desktop-portal
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
