name       : xdg-desktop-portal-kde
version    : 5.13.5
release    : 1
source     :
    - https://cdn.download.kde.org/stable/plasma/5.13.5/xdg-desktop-portal-kde-5.13.5.tar.xz : 8e587857ef720d9f879c6fd40fba8ba2b27d680831cde5d35e4c40d7db623745
license    : LGPL-2.1-or-later
component  : desktop.kde
summary    : Qt/KDE for xdg-desktop-portal
description: |
    A backend implementation for xdg-desktop-portal that is using Qt/KDE.
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(glib-2.0)
    - pkgconfig(libpipewire-0.2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - knotifications-devel
    - kwayland-devel
    - kwidgetsaddons-devel
rundeps    :
    - xdg-desktop-portal
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
