name       : xdg-desktop-portal-kde
version    : 5.16.2
release    : 18
source     :
    - https://cdn.download.kde.org/stable/plasma/5.16.2/xdg-desktop-portal-kde-5.16.2.tar.xz : 49d00aaa5ebf38f5b2c4b3110e53afa06973f949c782f59e10add8fe65fe95ff
license    : LGPL-2.1-or-later
component  : desktop.kde
summary    : Qt/KDE for xdg-desktop-portal
description: |
    A backend implementation for xdg-desktop-portal that is using Qt/KDE.
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(glib-2.0)
    - pkgconfig(libpipewire-0.2)
    - pkgconfig(Qt5Core)
    - cups-devel
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
    - knotifications-devel
    - kwayland-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
rundeps    :
    - xdg-desktop-portal
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
