name       : xdg-desktop-portal-kde
version    : 5.17.4
release    : 27
source     :
    - https://cdn.download.kde.org/stable/plasma/5.17.4/xdg-desktop-portal-kde-5.17.4.tar.xz : 58e6e61a95b324f80e5cf70c80841b87a73e613530d0ecfd6eb6446cbefc025e
license    : LGPL-2.1-or-later
component  : desktop.kde
summary    : Qt/KDE for xdg-desktop-portal
description: |
    A backend implementation for xdg-desktop-portal that is using Qt/KDE.
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(glib-2.0)
    - pkgconfig(libpipewire-0.2)
    - pkgconfig(Qt5Core)
    - cups-devel
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
    - knotifications-devel
    - kwayland-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
rundeps    :
    - xdg-desktop-portal
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
