name       : xdg-desktop-portal-kde
version    : 5.24.4
release    : 65
source     :
    - https://cdn.download.kde.org/stable/plasma/5.24.4/xdg-desktop-portal-kde-5.24.4.tar.xz : 11684916288bb4a452b75004e2d122a4a1264a562f7945af98d466e49c59dc1e
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-or-later
component  : desktop.kde
summary    : Qt/KDE for xdg-desktop-portal
description: |
    A backend implementation for xdg-desktop-portal that is using Qt/KDE.
builddeps  :
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(epoxy)
    - pkgconfig(dri)
    - pkgconfig(wayland-server)
    - cups-devel
    - kdeclarative-devel
    - kirigami2-devel
    - kio-devel
    - knotifications-devel
    - kwayland-devel
    - plasma-framework-devel
    - plasma-wayland-protocols-devel
rundeps    :
    - xdg-desktop-portal
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
