name       : xdg-desktop-portal-kde
version    : 5.14.2
release    : 5
source     :
    - https://cdn.download.kde.org/stable/plasma/5.14.2/xdg-desktop-portal-kde-5.14.2.tar.xz : ba98a1be265f823537c06ba946e0730f3acd88de7d1d71791f4fa0f2e4b84f8d
license    : LGPL-2.1-or-later
component  : desktop.kde
summary    : Qt/KDE for xdg-desktop-portal
description: |
    A backend implementation for xdg-desktop-portal that is using Qt/KDE.
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(glib-2.0)
    - pkgconfig(libpipewire-0.2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - knotifications-devel
    - kwayland-devel
    - kwidgetsaddons-devel
rundeps    :
    - xdg-desktop-portal
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
