name       : xdg-desktop-portal-kde
version    : 5.15.2
release    : 9
source     :
    - https://cdn.download.kde.org/stable/plasma/5.15.2/xdg-desktop-portal-kde-5.15.2.tar.xz : e4f6688c219d4be2a9ee9afd7f145514bd3ffad50bfaf4e1f887d9ff6800feff
license    : LGPL-2.1-or-later
component  : desktop.kde
summary    : Qt/KDE for xdg-desktop-portal
description: |
    A backend implementation for xdg-desktop-portal that is using Qt/KDE.
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(glib-2.0)
    - pkgconfig(libpipewire-0.2)
    - pkgconfig(Qt5Core)
    - cups-devel
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
    - knotifications-devel
    - kwayland-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
rundeps    :
    - xdg-desktop-portal
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
