name       : xdg-desktop-portal-kde
version    : 5.18.1
release    : 29
source     :
    - https://cdn.download.kde.org/stable/plasma/5.18.1/xdg-desktop-portal-kde-5.18.1.tar.xz : 6f0239e805704d7fc1f514c3e30646ebc9ad8b17201999b2754a6d3704b61ab0
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-or-later
component  : desktop.kde
summary    : Qt/KDE for xdg-desktop-portal
description: |
    A backend implementation for xdg-desktop-portal that is using Qt/KDE.
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(glib-2.0)
    - pkgconfig(libpipewire-0.2)
    - pkgconfig(Qt5Quick)
    - cups-devel
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdeclarative-devel
    - ki18n-devel
    - kirigami2-devel
    - kio-devel
    - knotifications-devel
    - kwayland-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - plasma-framework-devel
rundeps    :
    - xdg-desktop-portal
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
