name       : xdg-desktop-portal-kde
version    : 5.17.0
release    : 23
source     :
    - https://cdn.download.kde.org/stable/plasma/5.17.0/xdg-desktop-portal-kde-5.17.0.tar.xz : 5d6a54e764cc77c4d14cbae6ca76a4908fe93dcc7e36f641a1df1ce38b43da35
license    : LGPL-2.1-or-later
component  : desktop.kde
summary    : Qt/KDE for xdg-desktop-portal
description: |
    A backend implementation for xdg-desktop-portal that is using Qt/KDE.
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(glib-2.0)
    - pkgconfig(libpipewire-0.2)
    - pkgconfig(Qt5Core)
    - cups-devel
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
    - knotifications-devel
    - kwayland-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
rundeps    :
    - xdg-desktop-portal
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
