name       : xdg-desktop-portal-kde
version    : 5.14.0
release    : 3
source     :
    - https://cdn.download.kde.org/stable/plasma/5.14.0/xdg-desktop-portal-kde-5.14.0.tar.xz : 4983093c6fc657050a1531ac486321e763d0b9e0e522889c94126cc672f6f177
license    : LGPL-2.1-or-later
component  : desktop.kde
summary    : Qt/KDE for xdg-desktop-portal
description: |
    A backend implementation for xdg-desktop-portal that is using Qt/KDE.
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(glib-2.0)
    - pkgconfig(libpipewire-0.2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - knotifications-devel
    - kwayland-devel
    - kwidgetsaddons-devel
rundeps    :
    - xdg-desktop-portal
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
