name       : xdg-desktop-portal-kde
version    : 5.20.1
release    : 41
source     :
    - https://cdn.download.kde.org/stable/plasma/5.20.1/xdg-desktop-portal-kde-5.20.1.tar.xz : e09362a184e3814725206abe7d28e997851d4be0249c4b88619a51b1c3cfee2c
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-or-later
component  : desktop.kde
summary    : Qt/KDE for xdg-desktop-portal
description: |
    A backend implementation for xdg-desktop-portal that is using Qt/KDE.
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(dri)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(wayland-server)
    - cups-devel
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdeclarative-devel
    - ki18n-devel
    - kirigami2-devel
    - kio-devel
    - knotifications-devel
    - kwayland-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - plasma-framework-devel
    - plasma-wayland-protocols-devel
rundeps    :
    - xdg-desktop-portal
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
