name       : xdg-desktop-portal-kde
version    : 5.21.2
release    : 49
source     :
    - https://cdn.download.kde.org/stable/plasma/5.21.2/xdg-desktop-portal-kde-5.21.2.tar.xz : b4cf61e4f8d38081d35c8618985db5644128c8a08264304d7c2f2b8ef0c96abe
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-or-later
component  : desktop.kde
summary    : Qt/KDE for xdg-desktop-portal
description: |
    A backend implementation for xdg-desktop-portal that is using Qt/KDE.
builddeps  :
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(epoxy)
    - pkgconfig(dri)
    - pkgconfig(wayland-server)
    - cups-devel
    - kdeclarative-devel
    - kirigami2-devel
    - kio-devel
    - knotifications-devel
    - kwayland-devel
    - plasma-framework-devel
    - plasma-wayland-protocols-devel
rundeps    :
    - xdg-desktop-portal
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
