name       : xdg-desktop-portal-kde
version    : 5.21.3
release    : 50
source     :
    - https://cdn.download.kde.org/stable/plasma/5.21.3/xdg-desktop-portal-kde-5.21.3.tar.xz : 3012df6b6127bf7800b7be1fd8674213d0748e17050862dd13b2ca34f89a2117
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-or-later
component  : desktop.kde
summary    : Qt/KDE for xdg-desktop-portal
description: |
    A backend implementation for xdg-desktop-portal that is using Qt/KDE.
builddeps  :
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(epoxy)
    - pkgconfig(dri)
    - pkgconfig(wayland-server)
    - cups-devel
    - kdeclarative-devel
    - kirigami2-devel
    - kio-devel
    - knotifications-devel
    - kwayland-devel
    - plasma-framework-devel
    - plasma-wayland-protocols-devel
rundeps    :
    - xdg-desktop-portal
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
