name       : xdg-desktop-portal-kde
version    : 5.20.3
release    : 44
source     :
    - https://cdn.download.kde.org/stable/plasma/5.20.3/xdg-desktop-portal-kde-5.20.3.tar.xz : 565b4a1075de484a9c371d9812fb9c3d2006c3f65fe3433feb7aa3e4779048ca
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-or-later
component  : desktop.kde
summary    : Qt/KDE for xdg-desktop-portal
description: |
    A backend implementation for xdg-desktop-portal that is using Qt/KDE.
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(dri)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(wayland-server)
    - cups-devel
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdeclarative-devel
    - ki18n-devel
    - kirigami2-devel
    - kio-devel
    - knotifications-devel
    - kwayland-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - plasma-framework-devel
    - plasma-wayland-protocols-devel
rundeps    :
    - xdg-desktop-portal
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
