name       : xdg-desktop-portal-kde
version    : 5.14.4
release    : 8
source     :
    - https://cdn.download.kde.org/stable/plasma/5.14.4/xdg-desktop-portal-kde-5.14.4.tar.xz : 30ae4a2d668451957c7ff59f169a382d20da9874514329d374f4f3fd703e50dc
license    : LGPL-2.1-or-later
component  : desktop.kde
summary    : Qt/KDE for xdg-desktop-portal
description: |
    A backend implementation for xdg-desktop-portal that is using Qt/KDE.
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(glib-2.0)
    - pkgconfig(libpipewire-0.2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - knotifications-devel
    - kwayland-devel
    - kwidgetsaddons-devel
rundeps    :
    - xdg-desktop-portal
setup      : |
    %patch -p1 < $pkgfiles/Filechooser-fix.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
