name       : xdg-desktop-portal-kde
version    : 5.16.5
release    : 22
source     :
    - https://cdn.download.kde.org/stable/plasma/5.16.5/xdg-desktop-portal-kde-5.16.5.tar.xz : 4884652b642fb6e8db791a04e9d42b5fec53f28cc0f0d26f49eb2bdaaa1709df
license    : LGPL-2.1-or-later
component  : desktop.kde
summary    : Qt/KDE for xdg-desktop-portal
description: |
    A backend implementation for xdg-desktop-portal that is using Qt/KDE.
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(glib-2.0)
    - pkgconfig(libpipewire-0.2)
    - pkgconfig(Qt5Core)
    - cups-devel
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
    - knotifications-devel
    - kwayland-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
rundeps    :
    - xdg-desktop-portal
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
