name       : xdg-desktop-portal-kde
version    : 5.24.5
release    : 66
source     :
    - https://cdn.download.kde.org/stable/plasma/5.24.5/xdg-desktop-portal-kde-5.24.5.tar.xz : b59ccf65d29aef2ce6af9757a5c87eddd87b633fba2e45470f92b18b2ce5c6fe
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-or-later
component  : desktop.kde
summary    : Qt/KDE for xdg-desktop-portal
description: |
    A backend implementation for xdg-desktop-portal that is using Qt/KDE.
builddeps  :
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(epoxy)
    - pkgconfig(dri)
    - pkgconfig(wayland-server)
    - cups-devel
    - kdeclarative-devel
    - kirigami2-devel
    - kio-devel
    - knotifications-devel
    - kwayland-devel
    - plasma-framework-devel
    - plasma-wayland-protocols-devel
rundeps    :
    - xdg-desktop-portal
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
