name       : xdg-desktop-portal-kde
version    : 5.15.3
release    : 11
source     :
    - https://cdn.download.kde.org/stable/plasma/5.15.3/xdg-desktop-portal-kde-5.15.3.tar.xz : 27aefac029f9d7fdc2ad18b7b0f68c2695074633fdb6bee2cb7c5a5224f19581
license    : LGPL-2.1-or-later
component  : desktop.kde
summary    : Qt/KDE for xdg-desktop-portal
description: |
    A backend implementation for xdg-desktop-portal that is using Qt/KDE.
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(glib-2.0)
    - pkgconfig(libpipewire-0.2)
    - pkgconfig(Qt5Core)
    - cups-devel
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
    - knotifications-devel
    - kwayland-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
rundeps    :
    - xdg-desktop-portal
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
